pysoundfile.py
tests/test_argspec.py
tests/test_pysoundfile.py

Write currently always opens the file as `mode='w'`. `mode='x'` would be interesting as well.

Add option for exclusive creation to `write`

---

tests/test_pysoundfile.py

`test_write_non_seekable_file()` was writing the file `delme.please` and not removing it after the test.
Instead of using the file name directly, I changed this to use the parametrized fixture `file_w` which automatically removes the temporary file after usage (and even after a failure).
I also used that in 2 other test cases.
Finally, I changed the options for opening a Python file object to `buffering=False`, otherwise some of our tests wouldn't succeed because the data is not written to disk even if the corresponding `SoundFile` object is closed during the test.

Tests: properly remove written files

---

pysoundfile.py
tests/test_pysoundfile.py

`__repr__` could include the file name, samplerate and number of channels, and possibly the open mode.

Improve `__repr__`

---

pysoundfile.py

libsndfile can read from/write to a named pipe. We disabled this feature in #60 because we don't pass the file name directly to libsndfile anymore.
To make this possible again, we could check if a given file name is actually a pipe with
```python
import stat
import os
if stat.S_ISFIFO(os.stat(filename).st_mode):
else:
```
We'll probably have to catch an `OSError` if the file doesn't exist.
To try this, you can create a named pipe for writing:
mkfifo writepipe
cat writepipe
... and then use it:
```python
f = sf.open('writepipe', 'w', 44100, 1, format='au')
f.seekable()  # returns False
f.write([0.0, 0.1, 0.2])
f.close()
```
... or a named pipe for reading:
mkfifo readpipe
cat myfile.au > readpipe
... and read from it:
```python
f = sf.open('readpipe')
f.seekable()  # again False
f.read(10) …
```

Allow pipe read/write

---

pysoundfile.py
tests/test_pysoundfile.py

The documentation already mentions that closefd is only applicable if a
file descriptor is used.

Don't throw exception if closefd is given for non-fd

---

pysoundfile.py
tests/test_pysoundfile.py

- if a floating point format is chosen, the values get saved as is.
- if an integer format is chosen, garbage is written.
The second point is unpleasant. We could
- raise an error (this would be my choice)
- clip and warn
- scale and warn

What happens when the data written is bigger than [-1, 1)?

---

pysoundfile.py
tests/test_pysoundfile.py

Instead of
```Python
somestring.rsplit('.', 1)[-1]
```
we should use
```Python
os.path.splitext(somestring)[-1].lstrip('.')
```
This would correctly handle the currently failing cases where the filename is `"wav"` or `".wav"`.
We might want to add something like this to the unit tests:
```Python
for name_with_unknown_extension in "wav", ".wav", "wav.py":
with pytest.raises(TypeError) as excinfo:
sf.SoundFile(name_with_unknown_extension, 'w', 44100, 1)
assert "file extension" in str(excinfo.value)
```

SoundFile.__init__(): replace manual string manipulation with os.path.splitext

---

README.rst
doc/index.rst
setup.py
soundfile.py
tests/test_argspec.py
tests/test_pysoundfile.py

I always found the module name `pysoundfile` a bit clumsy to type and to speak about.
Also, `import pysoundfile as sf` didn't feel right, because `sf` isn't really an abbreviation of `pysoundfile`, it should rather be `psf`, but that's not nice, either.
I couldn't come up with a better suggestion, until I thought about possible package names for Debian (see #100). I think `python-soundfile` and `python3-soundfile` would be reasonable names for packages.
Which led me to the question: Why don't we just call the module `soundfile`?
This would be simpler, nicer to type and read, and the abbreviation `sf` would suddenly make sense:
```Python
import soundfile as sf
```
Also, `soundfile.SoundFile` looks more consistent to me than `pysoundfile.SoundFile`.
The project name on Github (the …

Rename module to "soundfile"

---

soundfile.py

`super()` is super for complicated class hierarchies, but for such simple cases I think it's not necessary.
I think to a large extent this is a matter of taste, I prefer to use `super()` only if its really necessary and if it actually makes a difference.
When searching around on the net, I found that the Python community seems to be torn about that issue.
It is considered everything between "super" and "harmful" ...

Use actual base class instead of super()

---

soundfile.py

It's important that we don't use empty braces `{}`, because this is not supported in Python 2.6.
Everything else should work fine.

Replace old-style string formatting with format() in the whole code base

---

soundfile.py
tests/test_argspec.py
tests/test_pysoundfile.py

This will revert the changes from #77.
Raising an error by default is useful in some cases, but it can also be harmful in other cases.
As far as I know, in most APIs the "write" function overwrites by default.
Also, e.g., the Unix commands `cp` and `mv` by default overwrite their target.
I think it's reasonable to assume that users expect overwriting behavior, therefore we should give it to them.
Once the default is changed to overwriting behavior, the argument `exclusive_creation` isn't that relevant anymore and it should be removed.
If users want to make sure that a file is not overwritten, they'll either have to check the existence first (e.g. with [`os.path.exists()`](https://docs.python.org/3/library/os.path.html#os.path.exists)) or they can use `f = SoundFile(..., mode='x')`.

Remove exclusive_creation argument from write() function

---

soundfile.py
tests/test_pysoundfile.py

Python file objects also [have this](https://docs.python.org/3/library/io.html#io.IOBase.truncate).
It looks like this can be done with the libsndfile command [SFC_FILE_TRUNCATE](http://www.mega-nerd.com/libsndfile/command.html#SFC_FILE_TRUNCATE).
Once we have this, we should replace the use of `os.open(..., os.O_TRUNC)` in `SoundFile.__init__()`.

Add SoundFile.truncate()

---

soundfile.py

As far as I can tell, reserving memory with `ffi.new()` isn't necessary here.
The `bytes` object returned from `encode()` can be directly passed to the CFFI function.

Avoid unnecessary call to ffi.new()

---

soundfile.py
tests/test_pysoundfile.py

Currently we check with `isinstance(file, str)`, which doesn't allow the Python 2 `unicode` type.
We should probably allow both "raw bytes" and "unicode" in both Python 2 and 3.
We would have to call `encode()` only on the "unicode" strings.
Alternatively, we could disallow Python 3 `bytes` objects, but I think it's better to allow them, because they are allowed for standard Python file objects, too.
I'm not sure which encoding is used by default, but we should check if we should probably change to `sys.getfilesystemencoding()`.
This idea is stolen from https://github.com/vokimon/python-wavefile
It's kind of annoying to check for unicode vs bytes, but I guess this would work in 2.6, 2.7 and 3.3+:
```Python
if isinstance(file, type(u"")):
if isinstance(file, type(b"")):
```
We could also …

Allow unicode filenames in Python 2

---

soundfile.py

Before, this was only done for file names (#68).
There are no tests yet, see #95.

Reset frames=0 in SFM_WRITE mode, also for file descriptors

---

README.rst
setup.py
soundfile.py

"The latest release" isn't accurate anymore.
We could also finally get rid of `__getitem__()`/`__setitem__()` and remove this section from the README.

Update "Breaking Changes" section

---

README.rst

I have been using Python(x,y) and WinPython distributions, and I haven't yet installed any new packages.  I was reading the installation instructions from PySoundFile, and I was confused on a few items.
The PySoundFile instructions say that you need the library libsndfile installed on your computer.  When using the Windows installers, isn't libsndfile included and its DLL put in the PySoundFile folder?
The PySoundFile instructions say that you also need CFFI.  Python(x,y), which is for Windows, already contains CFFI.  The Anaconda distribution contains CFFI for Linux and OSX.  The PySoundFile instructions suggest using WinPython, but wouldn't one of these other distributions be simpler since they already contain CFFI?
The Anaconda distribution now has installers for Python 2.7 and 3.4, …

Installation instructions

---

setup.py

This builds OS-dependent but Python-independent wheels.
I tested this on OSX, Win32, and Win64 and the wheels work fine.
The main point is that this should also work for `python setup.py bdist_wheel upload`.

Wheels are now os-dependent but python-independent

---

README.rst

I wanted to load a sound file from an URL and had a look at the example in the README:
```Python
from io import BytesIO
import soundfile as sf
import requests
f = BytesIO()
response = requests.get('http://www.example.com/my.flac', stream=True)
for data in response.iter_content(4096):
if data:
f.write(data)
f.seek(0)
data, samplerate = sf.read(f)
```
I found out that this has a lot of shortcomings:
1. the URL doesn't exist
2. there is no meaningful exception message if the URL doesn't exist
3. it needs an external library (`requests`)
4. the for-loop looks very complicated for such a simple task
5. the if-clause within looks strange
6. the "stream" stuff gives false hope that PySoundFile might support streaming from file objects, which it doesn't
Point 1: I don't know a good example URL. …

Pimp HTTP example in README

---

soundfile.py

Also, don't require `'read'` attr for virtual file in write mode.
Because with that, I could `SoundFile(GridOut)`, where `GridOut` is a MongoDB database object.

Don't require `'write'` attr for virtual file in read mode.

---

soundfile.py

I think #119 didn't go far enough regarding Unicode support.
It seems to work on Windows only as long as the file name can be encoded with `'mbcs'` encoding.
This works for me with innocuous names like `"äöüß.wav"`, but it doesn't work for more exotic names like `"☃.wav"`.
In this PR I'm activating the Windows-only function `sf_wchar_open()` to deal with Unicode file names on Windows.
I still don't know how to test all this in a meaningful way (see #122).
I did some informal tests on Windows XP and I'm able to write files with "strange" names, but those strange letters show up as rectangles when viewed in Windows Explorer (which I think is the expected behavior in my case).
I think it would be best to find a Windows system with some Asian language settings (or at least a system that can …

Support Unicode filenames in Windows with sf_wchar_open()

---

soundfile.py

Currently, we have this:
```Python
def vio_get_filelen(user_data):
try:
size = len(file)
except TypeError:
curr = file.tell()
file.seek(0, SEEK_END)
size = file.tell()
file.seek(curr, SEEK_SET)
return size
```
I suspect that the use of `len()` is a now obsolete artifact from the development in #1.
It was added there to seemingly support "streaming", but it turned out that this is not supported by the virtual IO call anyway.
Every supported file-like object *must have* the methods `seek()` and `tell()` anyway, so I think its superfluous to check with `len()` first.
Can we get rid of this remnant from the past?
I guess the cleaned-up version would look like this:
```Python
def vio_get_filelen(user_data):
curr = file.tell()
file.seek(0, SEEK_END)
size = file.tell()
file.seek(curr, SEEK_SET) …
```

Don't use len() in the virtual IO setup

---

tests/test_pysoundfile.py

I'm pretty sure that I tested this in #136, but for some reason the tests don't pass anymore.
It seems that libsndfile reads the old samples even though the length of the file should have been set to 1 in `sf.write()`.
Now I'm using `'w'` instead of `'r+'` for the write-only test, so the file is empty in the first place.

Tests: Add fixture for write-only file object

---

CONTRIBUTING.rst
doc/index.rst
tests/test_pysoundfile.py

As discussed in https://github.com/bastibe/PySoundFile/issues/29#issuecomment-49293101, we should document the tools we're using for the development of PySoundFile somewhere in the Sphinx documentation.
coverage:
https://github.com/bastibe/PySoundFile/issues/29#issuecomment-46548148
https://github.com/bastibe/PySoundFile/issues/29#issuecomment-49157194
py.test and file descriptors in Windows (see also #63):
https://github.com/bastibe/PySoundFile/pull/60#issuecomment-52160829

Add documentation for potential contributors

---

setup.py
soundfile.py
tests/test_pysoundfile.py

Instead of NumPy arrays, these would handle plain Python buffers.
This would allow a wider range of interoperability with Python libraries that use buffers, without forcing our users to convert their buffers into NumPy arrays.
These functions should then internally be used to implement our `read()` and `write()` methods.
Apart from the number of *items* (not *frames*), these methods could take one of the strings `'short'`, `'int'`, `'float'`, `'double'`.
They could also accept `'raw'` (or `'bytes'`?), which would provide an alternative solution to #25.
If we at some point split the implementation into several files, as suggested in https://github.com/bastibe/PySoundFile/issues/57#issuecomment-49281037, we could then create a low-level submodule which would have no dependencies on NumPy.

Add low-level methods read_buffer() and write_buffer()

---

.gitmodules
setup.py
soundfile.py

Prefixing this internal package name with an underscore should be less disruptive.

Rename pysoundfile_data -> _soundfile_data

---

soundfile.py
tests/test_pysoundfile.py

While I'm at suggesting breaking changes (see #132), I thought I might as well suggest another one ...
We discussed this already to quite some length in #16, but while I'm using it, I get the feeling that we may have chosen the wrong pill.
Arguments for `always_2d=True`:
* it's consistent in itself (everything is 2D, even mono signals)
* it's what you normally want in generic code (where you don't know if you get a mono or multi-channel file)
Arguments for `always_2d=False`:
* it's consistent with most of NumPy/SciPy (one-channel signals are 1D arrays)
* it's what you normally want in an interactive session (where you normally know if you are working on mono or multi-channel files)
I think we should simplify the interactive case, where being concise and the amount of typing matters most. …

Change default value of always_2d to False

---

README.rst
soundfile.py
tests/test_pysoundfile.py

We had some discussions in the past about argument ordering (#54, #78), but I don't think we really talked about the order of the filename and the array argument in `soundfile.write()`.
I always thought it would make sense to write the array first and the filename later.
I would ask "What?" first, before I want to know "Where?".
It also makes some kind of sense if you think about the array as an "input" argument and the filename as an "output" argument. I'd normally mention the input arguments before the output arguments.
However, while I'm using the function, I come to think more and more that the order actually seems strange.
What bugged me in the beginning, is that the array and its sample rate (which belong together), are actually separated in the call (and the sample rate is …

Change order of arguments in soundfile.write()

---

soundfile.py
tests/test_pysoundfile.py

I had to skip one test case for PyPy, because there seems to be a bug in PyPy 2.5, which says that an array is C-contiguous even if it isn't.
In PyPy 2.6.0 this seems to be fixed.
I couldn't find a way to get the PyPy version, so I just disabled it for all of PyPy.
Any idea how to get the PyPy version?
I changed a few exception types, but I'm not sure if those are correct.
I guess to some extent this is a matter of taste ...

Improve coverage

---

README.rst

There are surprisingly many bugs (even when not counting PEP-8 violations) in this (this is before #132):
```python
import soundfile as sf
format = {'format':'RAW', 'subtype':'FLOAT', 'endian':'FILE'}
data = sf.read('myfile.raw', dtype='float32', **format)
sf.write(data, 'otherfile.raw', **format)
```
This would be a variation that actually works (after merging #132):
```python
import soundfile as sf
format = dict(format='RAW', subtype='FLOAT', endian='FILE', samplerate=44100)
data, samplerate = sf.read('myfile.raw', channels=1, dtype='float32', **format)
assert samplerate == format['samplerate']
sf.write('otherfile.raw', data, **format)
```
Given this complexity, this is probably not such a "useful idiom" after all?
I hereby suggest to remove this example and replace it with an example …

RAW example in README is severely broken

---

soundfile.py

It is often desirable to get information about a sound file without reading all its data.

Implement `info` function

---

soundfile.py

I just found out that `SFC_SET_SCALE_FLOAT_INT_READ` is utterly useless.
If activated, it doesn't scale the data with some fixed value (as I and probably any sane person would have expected). Instead, it scales to the (absolute) largest occuring value!
I.e., if you have `[-2**-15, 0.0, 2**-15]` in your `'FLOAT'` file and read it as `'int16'`, you'll *not* get `[-1, 0, 1]`. Instead, you'll get `[-32767, 0, 32767]`!
I also tried `SFC_SET_SCALE_INT_FLOAT_WRITE`, which doesn't seem to do any such nonsense (but just scales with `2**-15`).
BTW, if `SFC_SET_SCALE_FLOAT_INT_READ` is *not* activated, any float value will be rounded to the next integer, so you'll typically get an array consisting only of `-1`, `0` and `1`, which is probably not that useful, either. But I don't see a way how we can …

Activate SFC_SET_SCALE_INT_FLOAT_WRITE?

---

soundfile.py

I happended to use PySoundFile with a development version of libsndfile and found that `available_subtypes()` lists the new ALAC subtype, but since there is no string for it, it just prints `None`.
This in turn leads to unknown subtypes being listed in `available_subtypes('WAV')`, because `subtype=None` passes the check for a valid format/subtype combo.
This PR replaces this with `'n/a'` and then adds another commit with the new subtype codes for ALAC.

Handle unsupported subtypes, add ALAC constants

---

doc/fake_cffi.py
setup.py
soundfile.py
tests/test_pysoundfile.py

Some time ago, they changed this in PEP 257.

Remove empty line before class docstrings

---

LICENSE

In other projects, I've also seen the project name in quotes, but I think it's more common without the quotes and to me it makes more sense.

Replace <ORGANIZATION> placeholder in LICENSE

---

soundfile.py
tests/test_pysoundfile.py

A similar function is mentioned in #23.
Any suggestions for a better function name?

Add a function to get the libsndfile version

---

setup.py

Without this, a non-Linux build from the tarball will fail.
See https://github.com/spatialaudio/python-sounddevice/issues/16 for an example error message.

Check for _soundfile_data directory in setup.py

---

doc/fake_cffi.py

PR #160 introduced those calls on module load, which broke the Sphinx autodoc generation.

DOC: Add missing member functions in fake CFFI class

---

soundfile.py

Currently there is no easy way to get the number of samples from the info class. It is retrieved as an intermediate value in a calculation, but then discarded. This adds that information as a attribute, and uses that attribute in the calculation.

Add the number of samples to the `info` class.

---

soundfile.py

It seems like I wasn't very attentive when contributing #72, since the docs weren't up-to-date with the function signatures and the implementation.

DOC: Fix "read/write buffer" docstrings

---

soundfile.py
tests/test_pysoundfile.py

Use dtype instead of ctype for "buffer" methods

---

setup.py

I don't know if in the meantime there is a saner way to support basically all Python versions in a non-pure wheel ...

Extend supported wheel versions with cp36 and pp33

---

README.rst

It's quite a long time ago, but we seem to have missed this in #26.
I guess the PR was created before #60 (where it was still accurate) but merged after it ...

DOC: Change 'rw' to 'r+' in README

---

soundfile.py

PySoundFile was searching in os.path.dirname(__file__) for the shared library, but after freezing the module __file__ might resolve to a location inside a zip file.
Therefore the path will now be backtracked until a real folder is found, which will then be used to locate the libsndfile library.

bugfix for packaging utilities like cx_Freeze

---

soundfile.py
tests/test_pysoundfile.py

This was deprecated in Nov 2016 (#179), which was released with version
0.9.0 in Feb 2017.
This is not urgent, we could also merge it after the next release if that seems more reasonable.

Remove 'ctype' argument from buffer_*() methods

---

README.rst
soundfile.py
tests/test_pysoundfile.py

Temporarily, `__bool__()` is added, which shall be removed again once
`__len__()` is removed.
See #199.

Add SoundFile.frames attribute and deprecate __len__()

---

MANIFEST.in
setup.py
soundfile.py
soundfile_build.py

Same request as for sounddevice:
https://github.com/spatialaudio/python-sounddevice/pull/102
This change adds one more file to the repository but doesn't really change anything else other than improving import time

use cffi's out-of-line mode to reduce import time

---

doc/conf.py
doc/fake__soundfile.py

Switching to out-of-line ABI mode (#211) broke this.
See also https://github.com/spatialaudio/python-sounddevice/pull/105.

DOC: fix fake import for API docs

---

doc/fake__soundfile.py
soundfile.py

ctypes find_library will simply return None if the library is not
found and passing this to ffi.dlopen will cause it to return stdlib
without error which is absolutely not what we want. This commit just
raises an exception if find_library returns None.
this also monkey patches ctypes find_library to disable searching
whenever building documentation

raise an exception if sndfile is not found

---

.travis.yml
tests/test_pysoundfile.py

When out of scope, SoundFile should vanish.
Explicit `gc.collect()` is required for this to pass in PyPy 7.0.0, but not in CPython 2.7.15+ or 3.6.8.

Test garbage collectability

---

soundfile.py
tests/test_pysoundfile.py

libsndfile error reporting is not thread safe, see https://github.com/erikd/libsndfile/issues/279 https://github.com/erikd/libsndfile/issues/610.
The patch does not attempt to fix that, but it changes the way errors are checked for in order to fix one specific race condition:
If opening a file not understood by libsndfile with `sf.SoundFile`, and then attempting to `.read()` from it, sometimes opening the file with `sf.SoundFile` does not report an error (due to the libsndfile race condition), and then the `.read()` fails. (As a consequence, librosa will not attempt to open the file using `audioread`, making `librosa.load` fail.)

Fix sf_open error checking when used concurrently

---

soundfile.py

Homebrew on Apple M1 uses a `/opt/homebrew/lib` instead of `/usr/local/lib`.
We are making sure we pick that up.

Find libsndfile.dylib on Apple M1

---

.github/workflows/python-package.yml

I've excluded Python 2.7 and 3.5 for my own sanity.  You can try to enable them later but I do not recommend it.  I've also excluded PyPy 3.7 on MacOS since Numpy compiles incorrectly for that version.
All Windows tests currently fail.  This is likely because the DLL's are not yet updated on master.  This PR can still be merged and used test the new Windows DLL's.

Add Python testing workflow.

---

soundfile.py

There has been a typo with `machine` variable resulting `NameError: name 'machine' is not defined` which is fixed here.

Fix NameError for _machine reference when loading 'sndfile' library on darwin

---

.github/workflows/python-package.yml
README.rst
build_wheels.py
setup.py
soundfile.py
tests/test_soundfile.py

A new release for soundfile.
Thank you, tennies, Hannes Helmholz, Christoph Boeddeker, Matt
Vollrath, Matthias Geier, Jacek Konieczny, Boris Verkhovskiy,
Jonas Haag, Eduardo Moguillansky, Panos Laganakos, Jarvy Jarvison,
Domingo Ramirez, Tim Chagnon, Kyle Benesch
- Adds binary wheels for macOS M1
- Improves compatibility with macOS, specifically for M1 machines
- Fixes file descriptor open for binary wheels on Windows and Python 3.5+
- Updates libsndfile to v1.0.31
- Adds get_strings method for retrieving all metadata at once
- Improves documentation, error messages and tests
- Displays length of very short files in samples
- Supports the file system path protocol (pathlib et al)

Release 0.11.0

---

README.rst
build_wheels.py
setup.py
soundfile.py

Dear soundfile community,
Find attached a beta release of the next version of soundfile, with
- libsndfile v1.2.0
- manylinux binary wheel
- improved libsndfile discovery
I would be grateful if you could test the wheels on the platform of your choice, and report back if they work, or if there are any issues.
[soundfile-0.12.0.wheels.zip](https://github.com/bastibe/python-soundfile/files/10695743/soundfile-0.12.0.wheels.zip)

Please test the beta release: V0.12.0

---

soundfile.py

Rather than trying to create the location for `_soundfile_data/` manually, simply import it and use its reported `__path__`
The existing method fails if using macos lib packaged with py2app because:
- starting path for soundfile is `/lib/python38.zip/soundfile.py`
- desired path fro soundfile_data  is `/lib/python3.8/_soundfile_data`
- the previous method of stepping back from the starting path never reaches this desired path (it tries `/lib/_soundfile_data` and fails)

More robust check for _soundfile_data package

---

README.rst

Fixes #333 
---
**Note**
I couldn't check the compiled HTML because I got the following error:
```
python setup.py build_sphinx
python-soundfile/venv/lib/python3.11/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!
********************************************************************************
Requirements should be satisfied by a PEP 517 installer.
If you are using pip, you can try `pip install --use-pep517`.
********************************************************************************
!!
dist.fetch_build_eggs(dist.setup_requires)
WARNING: The wheel package is not available.
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or: setup.py --help [cmd1 cmd2 ...]
or: setup.py --help-commands
or: …
```

updates README: in-memory virtual IO example

---

.github/workflows/python-package.yml

Recent test CI jobs on Ubuntu 20.04 were failed due to the out-dated apt package list cache of CI virtual machine.
- e.g. https://github.com/bastibe/python-soundfile/actions/runs/6613147987/job/18360406630
The package list should be updated before installing any apt package on CI.
This pull request add `apt-get update` before `apt-get install` to update apt package list.
In the future, maybe this installation command should be removed since `libsndfile.so` is already bundled in `soundfile` package on Linux x64 ( #364 ).
Or CI should be rewrited to test both the system library and the bundled library.
This pull request is intended to maintain the current CI behavior without major changes.
Failed CI log ( https://github.com/bastibe/python-soundfile/actions/runs/6613147987/job/18360406630 ) …

Linux CI: Update apt package list before installing package

---

.github/workflows/python-package.yml

This pull request updates macOS version on test CI to macOS 11.
GitHub no longer provides macOS 10.15 CI runners after 2022-12-01. And macOS 10.15 Catalina seems to be End-Of-Life.
- https://github.com/actions/runner-images/issues/5583
- https://endoflife.date/macos (Apple does not provide EOL information officially but no new 10.15.x release after macOS 10.15.7 security update 2022-005/2022-07-20)
- [About the security content of Security Update 2022-005 Catalina - Apple Support](https://support.apple.com/en-us/102769) (2022-07-20)
All recent CI jobs on macOS 10.15 were failed due to timeout.
- e.g. https://github.com/bastibe/python-soundfile/actions/runs/6613147987/job/18360408635
> test (macos-10.15, 3.6, x64)
> This request was automatically failed because there were no enabled …

macOS CI: Update macOS runner to macOS 11

---

.github/workflows/python-package.yml

Fix the CI error `ModuleNotFoundError: No module named '_soundfile'` on Python 3.7+.
Details: https://github.com/bastibe/python-soundfile/pull/420#issuecomment-1836425183
---
I guess I was mistaken in my perception that Windows + Python 3.11 has problems.
Instead, it seems that the Windows + pypy-3.8 test sometimes fails and sometimes succeeds.
- Succeeded test: https://github.com/aoirint/python-soundfile/actions/runs/7157130696/job/19487640731
- Failed test: https://github.com/aoirint/python-soundfile/actions/runs/7157094168/job/19487564694
Error message
```plain
Fatal error in the GIL or with locks: EnterNonRecursiveMutex(ms) [ffffffff,6]
```
It could be a pypy specific issue, but I am not familiar with it.

CI Error Workaround: Generate _soundfile.py before the package editable installation

---

setup.py

See discussion in #408. This may not be how you prefer to solve this.
It would be better if numpy were requested with a >= version number but I don't know which one is appropriate.

Require numpy for all installs

---

soundfile.py
tests/test_soundfile.py

The `blocks` method to read an audio in frame blocks with an optional overlap has a bug in the edge case when the file has less frames than the block size specified and the overlap specified is not 0. The full file and an overlap number of random values are returned in the output in this case.
When the method is called without a provided `out` array, it creates an empty array to store the output with the `np.empty` method with the shape corresponding to the block size argument (and the number of channels but that is not relevant for this problem). The default values in an array created by `np.empty` are not deterministic.
The file is then read into this `out` array up to the block size or the end of the file, whichever is shorter. The number of frames in the file plus the overlap size is …

Fixing blocks read with overlap for files shorter than block size

---

soundfile.py
soundfile_build.py
tests/test_argspec.py
tests/test_soundfile.py

Added interface to change compression level and bitrate mode as described in #390.
I was able to test it on Windows, but not on other platforms.

Add functions to change compression level and bitrate mode.

---

soundfile.py
tests/test_soundfile.py

In a previous [PR](https://github.com/bastibe/python-soundfile/pull/446) fixing blocks reading for files shorter than the specified blocksize, a regression was introduced resulting that even if the `fill_value` was specified, at most as many frames were read as the file had instead of the blocksize with the padding used. In this PR we add a fix so that if the fill_value is specified (and the output array is not), we will create an output array of blocksize regardless if the file doesn't have as many frames. Also added more unit tests to cover all these cases.
The regression mentioned above is part of version `0.13.0` of soundfile. Suggestion is to create a new version `0.13.1` with this fix included.

creating blocksize length output array in blocks reading if fill_value is set regardless of frames in file

---

CONTRIBUTING.rst

I noticed while working on PRs that `python setup.py test` doesn't run any tests anymore. This is due to the change that happened in [this PR](https://github.com/bastibe/python-soundfile/pull/452). Here I'm just updating the instructions to run the test the same way as the CI runs them. Also updating the instructions for running coverage as they didn't work the way they were before.

update testing instructions
